version: 2
jobs:
  build:
    working_directory: ~/lux
    docker:
      - image: zacharygolba/lux-framework:latest
        environment:
          NODE_ENV: test
          DATABASE_USERNAME: ubuntu
          JEST_JUNIT_OUTPUT: $CIRCLE_TEST_REPORTS/junit/test-results.xml
      - image: mysql:5.7
        environment:
          MYSQL_USER: ubuntu
          MYSQL_PASSWORD: ""
          MYSQL_DATABASE: lux_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
      - image: postgres:9.6
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: lux_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            yarn global remove lux-framework
            yarn install
            cd test/test-app
            yarn install
            cd ../../
      - run:
          name: Compile
          command: |
            yarn run clean
            NODE_ENV=production yarn build
            yarn link
            cd test/test-app
            lux build -e test
            cd ../../
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Check Types
          command: yarn flow
      - run:
          name: Seed Database
          command: |
            cd test/test-app
            lux db:migrate -e test --skip-build
            lux db:seed -e test --skip-build
            cd ../../
      - run:
          name: Test
          command: yarn test -- -i --forceExit
      - run:
          name: Report Coverage
          command: yarn codecov
