version: 2
jobs:
  build:
    docker:
      - image: zacharygolba/lux-framework:latest
        environment:
          NODE_ENV: test
          DATABASE_USERNAME: root
          JEST_JUNIT_OUTPUT: $CIRCLE_TEST_REPORTS/junit/test-results.xml
      - image: mysql:5.7
        environment:
          MYSQL_DATABASE: lux_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
      - image: postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: lux_test
    parallelism: 3
    working_directory: ~/lux
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run:
          name: Install Dependencies
          command: |
            yarn global remove lux-framework
            yarn install
            cd test/test-app
            yarn install
            cd ../../
      - save_cache:
          key: dependency-cache
          paths:
            - ~/lux/node_modules
            - ~/lux/test/test-app/node_modules
      - run:
          name: Compile
          command: |
            yarn run clean
            NODE_ENV=production yarn build
            yarn link
            cd test/test-app
            lux build -e test
            cd ../../
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Check Types
          command: yarn flow
      - run:
          name: Seed Database
          command: |
            if [ "${CIRCLE_NODE_INDEX}" != "2" ]; then
              cd test/test-app
              lux db:migrate -e test --skip-build
              lux db:seed -e test --skip-build
              cd ../../
            fi
      - run:
          name: Test
          command: yarn test -- -w=4 --colors
      - run:
          name: Report Coverage
          command: yarn codecov
